<a href="https://colab.research.google.com/github/GbotemiB/Housing_Project/blob/main/correction_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
path = '/content/drive/MyDrive/trans_50000.csv' 
path2 = '/content/drive/MyDrive/trans_100000.csv' 
path3 = '/content/drive/MyDrive/trans_150000.csv'

In [23]:
data = pd.read_csv(path, header=None)
data2 = pd.read_csv(path2, header=None)
data3 = pd.read_csv(path3, header=None)

In [24]:
len(data), len(data2), len(data3)

(50027, 50078, 50151)

In [25]:
data.tail()

,0,1,2,3,4
50022,51807,15.03.2021,"Surface d'activités : garage, industrie, artis...",fr,"Surface of activities: garage, industry, craft..."
50023,51808,01.05.2021,C'est à deux pas du parc de Valency ainsi qu'à...,fr,This 3-room apartment is located a stone's thr...
50024,51809,sofort,Durch die helle Fensterfronten bietet der Raum...,de,The room offers a lot of light through the bri...
50025,51810,01.05.2021,"Im Richti Areal, direkt beim Bahnhof Wallisell...",de,"In the Richti Areal, right next to the Wallise..."
50026,51811,01.05.2021,Suchen Sie etwas ganz Spezielles an zentraler ...,de,Are you looking for something very special in ...

In [27]:
data2.head()

,0,1,2,3,4
0,51812,nach Vereinbarung,"Idéalement placé entre Lausanne et Genève, Le ...",fr,"Ideally located between Lausanne and Geneva, t..."
1,51813,sofort,Nähe Hauptbahnhof und Europaalle vermieten wir...,de,We are now renting out several parking spaces ...
2,51814,nach Vereinbarung,"Coop, Apotheke und Drogerie sind einige Meter ...",de,"Coop, pharmacy and drugstore are a few meters ..."
3,51815,nach Vereinbarung,Ce bien d'exception se situe dans la 3ème étap...,fr,This exceptional property is located in the 3r...
4,51816,nach Vereinbarung,"An bester Lage, im Herzen von Bern, könnten si...",de,Your business premises could soon be in a prim...

In [28]:
data2.tail()

,0,1,2,3,4
50073,103571,sofort,"Belle maison individuelle de 4,5 pièces récemm...",fr,Beautiful detached house with 4.5 rooms recent...
50074,103572,01.05.2021,Bel appartement à 10min en vélo de l'hôpital R...,fr,Beautiful apartment 10min by bike from the Riv...
50075,103573,01.06.2021,Per 1. Juni 2021 oder nach Vereinbarung vermie...,de,"As of June 1, 2021 or by arrangement, we will ..."
50076,103574,nach Vereinbarung,Herrlicher freier und atemberaubender Blick üb...,de,Magnificent free and breathtaking view over th...
50077,103575,nach Vereinbarung,Cette charmante villa individuelle de 6.5 pièc...,fr,This charming detached 6.5 room villa is locat...

In [29]:
data3.head()

,0,1,2,3,4
0,103577,01.04.2021,Wir vermieten an ruhiger Lage eine geräumige 4...,de,We rent a spacious 4-room apartment in a quiet...
1,103578,nach Vereinbarung,Locaux meublés de bureaux comptoir chaises arm...,fr,Premises furnished with offices counter chairs...
2,103579,01.04.2021,MIETDAUER ab 1. April 2021 bis 30. September 2...,de,"RENTAL PERIOD from April 1, 2021 to September ..."
3,103580,nach Vereinbarung,"Cette maison, idéale pour une famille, bénéfic...",fr,"This house, ideal for a family, enjoys a rare ..."
4,103581,01.08.2021,"Das grosszügige, freistehende Einfamilienhaus ...",de,"The spacious, detached single-family house is ..."

In [30]:
data3.tail()

,0,1,2,3,4
50146,155355,not available,KurzbeschreibungDie Wohnung entsteht aus einem...,de,Brief descriptionThe apartment is created from...
50147,155356,nach Vereinbarung,"Fläche 1'068m2; Liegenschaft; Gebäude, Strasse...",de,"Area 1'068m2; Property; building, street, path..."
50148,155358,20.12.2022,Neue Förderung von Villen / Apartments in den ...,de,New promotion of villas / apartments on the he...
50149,155359,nach Vereinbarung,Appartement a louer à Vallorbe.3 pièces de 54m...,fr,Apartment for rent in Vallorbe. 3 rooms of 54m...
50150,155360,01.06.2021,Die zentral gelegene 3.5-Zimmer Wohnung liegt ...,de,The centrally located 3.5 room apartment is in...

In [7]:
data.columns = ['a', 'b', 'c', 'd', 'e']

In [8]:
data.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [9]:
data.loc[data['a'] =='51807']

,a,b,c,d,e
50022,51807,15.03.2021,"Surface d'activités : garage, industrie, artis...",fr,"Surface of activities: garage, industry, craft..."

In [10]:
data.loc[data['a'] == '51811']

,a,b,c,d,e
50026,51811,01.05.2021,Suchen Sie etwas ganz Spezielles an zentraler ...,de,Are you looking for something very special in ...

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).